In [2]:
import torch
import numpy

### Suppose eqn=> y=x^2

### Backpropogation => y= 2x



In [63]:
x= torch.tensor(4.0, requires_grad= True) #requires_grad = True for backpropogation necesaary

In [64]:
x

tensor(4., requires_grad=True)

In [6]:
y = x**2

In [7]:
y

tensor(16., grad_fn=<PowBackward0>)

In [8]:
#Backpropogation
y.backward()

In [11]:
print(x.grad)

tensor(8.)


What if the tensor were a matrix, as they are in ANN

In [79]:
lst = [[1.,2.,3.], [7.,5.,6.], [0.,7.,2.]]
torch_input = torch.tensor(lst, requires_grad = True)

In [80]:
torch_input

tensor([[1., 2., 3.],
        [7., 5., 6.],
        [0., 7., 2.]], requires_grad=True)

In [81]:
y = torch_input**2 + 3
y

tensor([[ 4.,  7., 12.],
        [52., 28., 39.],
        [ 3., 52.,  7.]], grad_fn=<AddBackward0>)

In [82]:
z=y.sum()

In [83]:
z

tensor(204., grad_fn=<SumBackward0>)

In [84]:
z.backward()

In [85]:
torch_input.grad

tensor([[ 2.,  4.,  6.],
        [14., 10., 12.],
        [ 0., 14.,  4.]])