# Tensors Basic

In [2]:
import torch
import numpy as np

In [3]:
lst=[2,3,4,5]
np_lst= np.asarray(lst)
tensor = torch.from_numpy(np_lst)
tensor

tensor([2, 3, 4, 5])

In [4]:
print(tensor[0], tensor[0:], tensor[:2])

tensor(2) tensor([2, 3, 4, 5]) tensor([2, 3])


In [11]:
tensor[2]=100
print(tensor, np_lst)

tensor([  2,   3, 100,   5]) [  2   3 100   5]


In [15]:
tensor_f32 = torch.from_numpy(np_lst).to(torch.float32)
print(tensor_f32)

tensor([  2.,   3., 100.,   5.])


# Operations

In [17]:
a= torch.tensor([2,4,5])
a*5

tensor([10, 20, 25])

In [18]:
b= torch.tensor([9,9,9])
a+b

tensor([11, 13, 14])

In [22]:
a*b

tensor([18, 36, 45])

In [25]:
(a*b).sum()

tensor(99)

In [23]:
a.dot(b)

tensor(99)

In [20]:
c=torch.tensor([[7],[9],[4]])
b*c

tensor([[63, 63, 63],
        [81, 81, 81],
        [36, 36, 36]])

In [21]:
b.sum()

tensor(27)