In [1]:
import numpy as np

Creating a matrix

In [4]:
matrix= np.array([[2,3,4], [4,5,6], [9,7,6]])
print(matrix)
matrix.shape

[[2 3 4]
 [4 5 6]
 [9 7 6]]


(3, 3)

Random matrix

In [7]:
random_matrix= np.random.rand(3,3)

In [8]:
random_matrix

array([[0.46772159, 0.36373256, 0.08384916],
       [0.86230494, 0.14466752, 0.04676936],
       [0.3320911 , 0.13446353, 0.21384121]])

In [13]:
random_integer_matrix= np.random.randint(low=1,high= 100,size=(3,3))

print(random_integer_matrix)

[[79 71 39]
 [15 17 28]
 [22 44 13]]


Types of Matrix

In [16]:
ones_matrix= np.ones(shape=(3,3))
ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones_int_matrix= np.ones(shape=(3,3), dtype= int)
ones_int_matrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
zeros_matrix= np.zeros(shape=(3,3), dtype= int)
zeros_matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
identity_matrix= np.eye(3,3, dtype= int)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Transpose of Matrix

In [27]:
a= np.random.randint(100, size=(3,3))
a

array([[51, 54, 19],
       [59, 19, 86],
       [15, 98, 37]])

In [28]:
transpose_a= np.transpose(a)
transpose_a

array([[51, 59, 15],
       [54, 19, 98],
       [19, 86, 37]])

Matrix Addition

In [40]:
m1= np.random.randint(5, size=(3,3))
m2= np.random.randint(5, size=(3,3))

print(m1, "\n \n", m2)

[[3 2 2]
 [3 1 4]
 [1 1 3]] 
 
 [[1 1 2]
 [3 0 2]
 [3 4 4]]


In [41]:
m3= m1+m2
m3

array([[4, 3, 4],
       [6, 1, 6],
       [4, 5, 7]])

Matrix Multiplication

In [42]:
m4= m1*2 #scalar
m4

array([[6, 4, 4],
       [6, 2, 8],
       [2, 2, 6]])

In [43]:
m5= m1*m2 #matrix not right, element wise multiplication

m7= np.dot(m1,m2) #correct way
print("m5: " ,m5, "\n\n" , "m7: " , m7 )

m5:  [[ 3  2  4]
 [ 9  0  8]
 [ 3  4 12]] 

 m7:  [[15 11 18]
 [18 19 24]
 [13 13 16]]


Matrix Substraction

In [36]:
m6= m1-m2
m6

array([[ 58,   8,   1],
       [ -9, -18,  12],
       [  0, -39,  -4]])